#!/usr/bin/ennv bash
#configs the web server

#stops any process listening on port 80
sudo fuser -k 80/tcp

cd /etc/nginx/sites-enabled/ || exit;
rm default
ln -s /etc/nginx/sites-available/default default;
service nginx restart
