#!/usr/bin/env bash
# script displays content of a file using the while loop and IFS
while IFS=':' read -r -a shebang;
do
        echo "The user ${shebang[0]} is part of the ${shebang[3]} gang, lives in ${shebang[5]} and \
               rides ${shebang[2]}'s place is protected by the passcode ${shebang[1]}, more \
               info about the user here: ${shebang[4]}"
done < /etc/passwd;
