#!/usr/bin/env bash
# my script displays diff messages based on the loop iteration

ki=1
while [ $ki -le 10 ];
do

        if [ $ki -eq 4 ];
        then
                 echo "bad luck"
        elif [ $ki -eq 8 ];
        then
                 echo "good luck"
        else
                 echo "Best School"
        fi
        ((ki++))
done
